# -*- coding: utf-8 -*-
"""HuggingFace Testimonies.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TEZRbK0kZVMlvUJD5uIDBCyLYuudUn4z
"""


import os
import re
import time
import pandas as pd
import numpy as np
import copy
import pypandoc
from datasets import load_dataset
from bs4 import BeautifulSoup
from pdf2docx import Converter
import pypandoc

ds = load_dataset("ushmm-pdfs")

"""## Phase 1

Extract HTML and save it into a separate file to read from later to use as a restore point
"""

print(ds)

ds['train'][0]['html']

print(ds)

for i in range(ds['train'].num_rows):
    name = ds['train'][i]['rg']
    html = ds['train'][i]['html']
    data[name] = html
    file = open('./HTML/'+name+'.txt', 'w')
    file.write(html)
    file.close()

data[file_name]

"""## Phase 2

Read from HTML and extract text contents
"""

# Read FROM HTML Folder
directory_path = './HTML'
file_list = sorted(os.listdir(directory_path))
files = [file for file in file_list if file.endswith(".txt")]
data = {}

for file_name in files:
    file = open('./HTML/'+file_name, 'r')
    file_content = file.readlines()
    stripped_lines = [content.strip() for content in file_content]

    file.close()
    data[file_name] = stripped_lines

file_name = "RG-50.549.04.0004_trs_en_cleaned.txt"
current_file = data[file_name]
current_text = ""
for i in range(len(current_file)):
    current_text += current_file[i]
current_text

data[list(data.keys())[-1]]

html_content = ds['train'][1]['html']

#content = '<dialogue class=""><p></p></dialogue><dialogue class="Question"><p><p>Q: Why did your family move?</p></p></dialogue>'
current_text = """
<dialogue class=""><p></p></dialogue>
<dialogue class="Answer">
  <p>
    <p>A: No, they were not made for stories for children. They were as gruesome as he could remember them. He would tell me -- he didn't go through the concentration camps, so he didn't tell me those kind of stories. He told me how his father was killed in front of him, how his sisters were killed. I knew the story about my grandfather, I can't tell you what age I -- I knew that he tried to -- my mother's father, how he escaped, and how he tried to come back and find her. I -- I can't tell you when these started, but I-I always had these stories.</p>
    <p>
      <span class="page-break" number="1"></span> Interview with Esther Dezube deg December 7, 2000
    </p>
  </p>
</dialogue>
"""

#data[list(data.keys())[-1]]
dialogue = BeautifulSoup(current_text, 'html.parser').find_all(True)
dialogue = BeautifulSoup(str(dialogue[2]), 'html.parser').find_all('dialogue')

# dialogue[1]['class']
#data[list(data.keys())[-1]]
dialogue[0].text.strip()





# Specify the paths to your PDF and output Word file
pdf_file = "./PDFs/ushmm-pdfs/pdfs/RG-50.549.04.0004_trs_en.pdf"
docx_file = "test2.docx"

# Convert PDF to Word
cv = Converter(pdf_file)
cv.convert(docx_file)
cv.close()



# Example file:
docxFilename = './test2.docx'
output = pypandoc.convert_file(docxFilename, 'plain', outputfile="somefile2.txt")
output

pandoc